config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks , only: [:create, :destroy]
  devise_for :users
  get 'welcome/index'
  root 'welcome#index'
  get 'my_portfolio' , to: 'users#my_portfolio'
  get 'search_stock' ,to: 'stocks#search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/Utility.rb
module Utility

 def say_hi
     puts 'welcome to Utility'
   end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock.rb
class Stock < ApplicationRecord
has_many :user_stocks
has_many :users, through: :user_stocks

validates :name, :ticker , presence: true

  def self.new_lookup(ticker_symbol)
    client = IEX::Api::Client.new(
      publishable_token: 'Tpk_42731396d5fe4af5a5e5cdce8b83aab3',
      secret_token: 'Tsk_8cf6ec8f5ecb4e3993b714f90fa29249',
      endpoint: 'https://sandbox.iexapis.com/v1')

      begin
      new(ticker: ticker_symbol, name: client.company(ticker_symbol).company_name, last_price: client.price(ticker_symbol))
      rescue => exception
        return nil
      end
   end


   def self.check_db(ticker_symbol)
     where(ticker: ticker_symbol).first
   end


end

app/models/stock_symbol.rb
class StockSymbol < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  include Utility
  extend Utility

  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable





  def stock_already_tracked?(ticker_symbol)
      stock= Stock.check_db(ticker_symbol)
      return false unless stock
      stocks.where(id: stock.id).exists?
  end


  def under_stock_limit?
    stocks.count < 10
  end



  def can_track_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_tracked?(ticker_symbol)
  end

end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search
    @client = IEX::Api::Client.new(
      publishable_token: 'Tpk_42731396d5fe4af5a5e5cdce8b83aab3',
      secret_token: 'Tsk_8cf6ec8f5ecb4e3993b714f90fa29249',
      endpoint: 'https://sandbox.iexapis.com/v1')

    if params[:stock].present?
       ticker_symbol= StockSymbol.where(name: params[:stock]).first.symbol
      @stock= Stock.new_lookup(ticker_symbol)
        if @stock
          respond_to do |format|
            format.js {render partial: 'users/result'}
          end
        #render 'users/my_portfolio'
        else
            respond_to do |format|
              flash.now[:alert]="Please Enter Valid Symbol to Search"
                format.js {render partial: 'users/result'}
            end


        #  redirect_to my_portfolio_path
        end
    else
      respond_to do |format|
        flash.now[:alert]="Please Enter   Symbol to Search"
        format.js {render partial: 'users/result'}
      end
      #   redirect_to my_portfolio_path
    end
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController

  def create
    stock= Stock.check_db(params[:ticker])
    if stock.blank?
      stock = Stock.new_lookup(params[:ticker])
      stock.save
    end
    @user_stock=UserStock.create(user: current_user, stock: stock )
    flash[:notice]="Stock #{stock.name} saved to Your Portfolio"
    redirect_to my_portfolio_path
  end

  def destroy
    stock= Stock.find(params[:id])
    user_stock=  UserStock.where(user_id: current_user.id, stock_id: stock).first
    user_stock.destroy
    flash[:notice]= "#{stock.ticker} was successfully removed from your Portfolio "
    redirect_to my_portfolio_path

    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @stocks1=StockSymbol.all
    @names = Array.new
    @stocks1.each do |s|
      @names.push(s.name)
    end

    @stocks= current_user.stocks

  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index


 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_messages.html.erb
<% if notice %>
	<div class='alert alert-success'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= notice %>
	</div>
<% end %>

<% if alert %>
	<div class='alert alert-danger'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= alert %>
	</div>
<% end %> 

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">

  <%= link_to 'FinanceTracker', root_path, class: 'navbar-brand' %>

  <% if current_user %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item <%= 'active' if request.path == my_portfolio_path %>">
            <%= link_to 'My Portfolio', my_portfolio_path, class: 'nav-link' %>
      </li>
      <li class="nav-item  ">
            <%= link_to 'Value Investment', '#', class: 'nav-link' %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#"><%=current_user.email %></a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
    <li class="nav-item">
      <%= link_to("Logout", destroy_user_session_path, class: "btn btn-danger logout-btn", method: :delete) %>
    </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
  <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


      <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
       <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
      <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>



    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/stocks/_list.html.erb
<div class="row">
  <div class="col-9">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th scope="col">Ticker</th>
          <th scope="col">Name</th>
          <th scope="col">Price</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        <% @stocks.each do |s| %>
        <tr>
          <th scope="row"><%= s.ticker %></th>
          <td><%= s.name %></td>
          <td><%= s.last_price %></td>
          <td><%= link_to 'Remove' ,  user_stock_path(s), method: :delete, data: {confirm:'Are you sure?'}, class: "btn btn-sm btn-warning" %></td>
        </tr>
         <% end %>
      </tbody>
    </table>

  </div>
</div>

app/views/users/_result.html.erb
<div class="result-block">
  <%= render 'layouts/messages' %>

</div>


<% if @stock %>
<div class="card card-header result-block col-sm-9  ">

  <table class="table table-sm table-bordered">

    <tbody>
      <tr>

        <td><b>Symbol:</b></td>
        <td><%= @stock.ticker %></td>
        <td><b>52 Week High</b></td>
        <td><%= @client.key_stats(@stock.ticker).week_52_high %></td>
      </tr>
      <tr>

        <td><b>Name:</b></td>
        <td><%= @stock.name %></td>
        <td><b>52 Week low</b></td>
        <td><%= @client.key_stats(@stock.ticker).week_52_low %></td>
      </tr>
      <tr>
        <td><b>last_price:</b></td>
        <td><%= @stock.last_price %></td>

        <td><b>P/E Ratio</b></td>
        <td><%= @client.key_stats(@stock.ticker).pe_ratio %></td>
      </tr>
    </tbody>
  </table>












  <% if current_user.can_track_stock?(@stock.ticker) %>
      <%= link_to 'Add to Portfolio', user_stocks_path(user: current_user, ticker:  @stock.ticker), class: 'btn btn-success', method: :post %>
  <% else %>
    <span class="label">
      You are Already Tracking
    </span>
  <% end %>
</div>
<% end %>

app/views/users/_result.js.erb
document.querySelector('#results').innerHTML= '<%= j render 'users/result.html' %>'  

app/views/users/my_portfolio.html.erb
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>


<script>
  $( function() {
    var availableTags =  <%=raw @names  %>;
    $( "#symbols" ).autocomplete({
      source: availableTags
    });
  } );
</script>






<h1>My Portfolio</h1>
<div class="search-area">
<h3> Search Stock <h3>
  <%= form_tag search_stock_path, remote:true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
         <%= text_field_tag  :stock , params[:stock] , id: 'symbols', placeholder: "Search like AMZN, GOOG, MSFT.....", autofocus: true, class: "form-control form-control-lg"   %>
      </div>
      <div class="col-sm-3 no-left-padding">
       <%= button_tag type: :submit , class: "btn btn-success" do %>
        <%= fa_icon 'search 2x' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div id="results">
</div>

<%  if !@stocks.empty? %>
 <%= render 'stocks/list' %>
<% end %>

app/views/welcome/index.html.erb
<%= javascript_pack_tag 'test'   %>

<h1>Welcome To Finance Tracker APP</h1>
   <%= link_to 'Go To Portfolio', my_portfolio_path, class: 'btn btn-success' %>
<br>
<br>
<%= link_to 'Sign Out', destroy_user_session_path, class: 'btn btn-success', method: :delete %>


<br>
<br><br>
<b>Date From JavaScript </b>
<p id="demo"></p>